/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLMobilebackendFilterDto.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobilebackend/v1
// Description:
//   This is an API
// Classes:
//   GTLMobilebackendFilterDto (0 custom class methods, 4 custom properties)

#import "GTLMobilebackendFilterDto.h"

#import "GTLMobilebackendFilter.h"

// ----------------------------------------------------------------------------
//
//   GTLMobilebackendFilterDto
//

@implementation GTLMobilebackendFilterDto
@dynamic datastoreFilter, operatorProperty, subfilters, values;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"operator"
                                forKey:@"operatorProperty"];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [GTLMobilebackendFilterDto class], @"subfilters",
      [NSObject class], @"values",
      nil];
  return map;
}

@end
