/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLMobilebackendEntityListDto.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobilebackend/v1
// Description:
//   This is an API
// Classes:
//   GTLMobilebackendEntityListDto (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLMobilebackendEntityDto;

// ----------------------------------------------------------------------------
//
//   GTLMobilebackendEntityListDto
//

@interface GTLMobilebackendEntityListDto : GTLObject
@property (retain) NSArray *entries;  // of GTLMobilebackendEntityDto
@end
