/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLMobilebackendQueryDto.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobilebackend/v1
// Description:
//   This is an API
// Classes:
//   GTLMobilebackendQueryDto (0 custom class methods, 9 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLMobilebackendFilterDto;

// ----------------------------------------------------------------------------
//
//   GTLMobilebackendQueryDto
//

@interface GTLMobilebackendQueryDto : GTLObject
@property (retain) GTLMobilebackendFilterDto *filterDto;
@property (copy) NSString *kindName;
@property (retain) NSNumber *limit;  // intValue
@property (copy) NSString *queryId;
@property (copy) NSString *regId;
@property (copy) NSString *scope;
@property (retain) NSNumber *sortAscending;  // boolValue
@property (copy) NSString *sortedPropertyName;
@property (retain) NSNumber *subscriptionDurationSec;  // intValue
@end
