/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLMobilebackendEntityDto.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobilebackend/v1
// Description:
//   This is an API
// Classes:
//   GTLMobilebackendEntityDto (0 custom class methods, 8 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLMobilebackendEntityDto
//

@interface GTLMobilebackendEntityDto : GTLObject
@property (retain) GTLDateTime *createdAt;
@property (copy) NSString *createdBy;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (copy) NSString *identifier;

@property (copy) NSString *kindName;
@property (copy) NSString *owner;
@property (retain) id properties;
@property (retain) GTLDateTime *updatedAt;
@property (copy) NSString *updatedBy;
@end
