/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLMobilebackendFilterDto.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobilebackend/v1
// Description:
//   This is an API
// Classes:
//   GTLMobilebackendFilterDto (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLMobilebackendFilter;
@class GTLMobilebackendFilterDto;

// ----------------------------------------------------------------------------
//
//   GTLMobilebackendFilterDto
//

@interface GTLMobilebackendFilterDto : GTLObject
@property (retain) GTLMobilebackendFilter *datastoreFilter;

// Remapped to 'operatorProperty' to avoid language reserved word 'operator'.
@property (copy) NSString *operatorProperty;

@property (retain) NSArray *subfilters;  // of GTLMobilebackendFilterDto
@property (retain) NSArray *values;  // of any JSON type
@end
