/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLMobilebackendConstants.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobilebackend/v1
// Description:
//   This is an API

#import <Foundation/Foundation.h>

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLDefines.h"
#else
  #import "GTLDefines.h"
#endif

// AccessMode
GTL_EXTERN NSString * const kGTLMobilebackendAccessModePrivate;  // "PRIVATE"
GTL_EXTERN NSString * const kGTLMobilebackendAccessModePublicRead;  // "PUBLIC_READ"
GTL_EXTERN NSString * const kGTLMobilebackendAccessModePublicReadForAppUsers;  // "PUBLIC_READ_FOR_APP_USERS"
