/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLMobilebackendBlobAccess.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobilebackend/v1
// Description:
//   This is an API
// Classes:
//   GTLMobilebackendBlobAccess (0 custom class methods, 3 custom properties)

#import "GTLMobilebackendBlobAccess.h"

// ----------------------------------------------------------------------------
//
//   GTLMobilebackendBlobAccess
//

@implementation GTLMobilebackendBlobAccess
@dynamic accessUrl, mandatoryHeaders, shortLivedUrl;
@end
