/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLMobilebackend_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobilebackend/v1
// Description:
//   This is an API

#import "GTLMobilebackendConstants.m"

#import "GTLMobilebackendBlobAccess.m"
#import "GTLMobilebackendEntityDto.m"
#import "GTLMobilebackendEntityListDto.m"
#import "GTLMobilebackendFilter.m"
#import "GTLMobilebackendFilterDto.m"
#import "GTLMobilebackendQueryDto.m"

#import "GTLQueryMobilebackend.m"
#import "GTLServiceMobilebackend.m"
