/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLMobilebackendQueryDto.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobilebackend/v1
// Description:
//   This is an API
// Classes:
//   GTLMobilebackendQueryDto (0 custom class methods, 9 custom properties)

#import "GTLMobilebackendQueryDto.h"

#import "GTLMobilebackendFilterDto.h"

// ----------------------------------------------------------------------------
//
//   GTLMobilebackendQueryDto
//

@implementation GTLMobilebackendQueryDto
@dynamic filterDto, kindName, limit, queryId, regId, scope, sortAscending,
         sortedPropertyName, subscriptionDurationSec;
@end
