/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLMobilebackendConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mobilebackend/v1
// Description:
//   This is an API

#import "GTLMobilebackendConstants.h"

// AccessMode
NSString * const kGTLMobilebackendAccessModePrivate            = @"PRIVATE";
NSString * const kGTLMobilebackendAccessModePublicRead         = @"PUBLIC_READ";
NSString * const kGTLMobilebackendAccessModePublicReadForAppUsers = @"PUBLIC_READ_FOR_APP_USERS";
